[package]
name = "common-profling"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies] # In alphabetical order
# Workspace dependencies
common-exception = {path = "../exception"}

# Crates.io dependencies
pprof = { version = "0.4", features = ["flamegraph", "protobuf"] }
tokio = { version = "1.6"}
